version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    environment:
    steps:
      - checkout
      - run: git clone git@github.com:OtoAnalytics/build-scripts.git ~/build-scripts
      - run: cd ~/build-scripts && git checkout master
      - run: echo $MVN_SETTINGS_XML > ~/.m2/settings.xml
      - run: sudo cp ~/build-scripts/circle2/aws-maven-assembler-fat.jar ${M2_HOME}/lib/aws-maven-assembler-fat.jar
      - run: mvn deploy -DskipITs

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
